# Generated by Django 3.2.8 on 2021-10-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_forgetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first',
            field=models.BooleanField(default=True, verbose_name='is first'),
        ),
    ]
