# Generated by Django 3.2.8 on 2021-10-14 08:43

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organizationfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationfile',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='organizationfile',
            name='file',
            field=models.FileField(default=1, upload_to=core.utils.get_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizationfile',
            name='title',
            field=models.CharField(default=1, max_length=128, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
