# Generated by Django 3.2.8 on 2021-10-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20211009_0945'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizationuser',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='user-organization'),
        ),
    ]
