# Generated by Django 3.2.8 on 2021-10-15 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20211014_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationfile',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
