# Generated by Django 3.2.8 on 2021-10-09 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('organization', '0003_auto_20211009_0945'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('desc', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoneMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('taken_from', models.CharField(blank=True, max_length=128, null=True, verbose_name='Patient')),
                ('status', models.CharField(choices=[('fridge', 'fridge'), ('transfer', 'transfer'), ('orbone', 'orbone')], default='fridge', max_length=48)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.hospital', verbose_name='Hospital')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization', verbose_name='Organization')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Taken By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
