# Generated by Django 3.2.8 on 2021-10-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0003_auto_20211009_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=256, verbose_name='Hospital')),
                ('organizations', models.ManyToManyField(to='organization.Organization', verbose_name='Organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
