# Generated by Django 3.2.8 on 2021-10-09 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationuser_user-organization'),
        ('warehouse', '0002_auto_20211009_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='Warehouse Name')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
