# Generated by Django 3.2.8 on 2021-10-08 13:37

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0002_auto_20211008_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('note', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Note Detail')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.get_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.utils.get_upload_path)),
                ('show_status', models.PositiveSmallIntegerField(choices=[(1, 'Herkes Görebilir'), (2, 'Şirket İçi'), (3, 'Kendim')], default=2, verbose_name='Kimler Görüntüler')),
                ('pin', models.CharField(blank=True, default='#4CAF50', max_length=24, null=True, verbose_name='Pin')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='note_content')),
                ('created_by_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note_created_by', to='organization.organizationuser', verbose_name='OluşturanId')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
