# Generated by Django 3.2.8 on 2021-10-09 07:46

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
        migrations.RemoveField(
            model_name='note',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.get_upload_path),
        ),
    ]
