# Generated by Django 3.2.8 on 2021-10-12 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TissueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('desc', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TissueMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.CharField(blank=True, max_length=128, null=True, verbose_name='Patient')),
                ('status', models.CharField(choices=[('fridge', 'fridge'), ('transfer', 'transfer'), ('orbone', 'orbone')], default='fridge', max_length=48)),
                ('taken_time', models.DateTimeField(auto_now=True, verbose_name='Taken Time')),
                ('transfer_time', models.DateTimeField(blank=True, null=True, verbose_name='Transfer Time')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Delivery Time')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bones_taken_by', to=settings.AUTH_USER_MODEL, verbose_name='Taken By')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_tissues', to='warehouse.hospital', verbose_name='Hospital')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_bones', to='organization.organization', verbose_name='Organization')),
                ('tissue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tissue_materials', to='tissue.tissuetype', verbose_name='Tissue Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
