# Generated by Django 3.2.8 on 2021-10-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tissue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tissuematerial',
            name='taken_time',
            field=models.DateTimeField(verbose_name='Taken Time'),
        ),
    ]
