# Generated by Django 3.2.8 on 2021-10-18 06:35

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tissue', '0002_alter_tissuematerial_taken_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TissueFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('file', models.FileField(upload_to=core.utils.get_upload_path)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tissue_tissuefile', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('tissue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tissue_files', to='tissue.tissuematerial', verbose_name='Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
