# Generated by Django 3.2.8 on 2021-10-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tissue', '0003_tissuefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tissuetype',
            old_name='title',
            new_name='name',
        ),
    ]
